#!/bin/bash

set -e
set -x

env

. /usr/share/mkapp/functions

if [ "$PACKAGING" ]; then
  build -F

  #if [ "$PUBLISH" ]; then
    #publish_debs
    #publish_ivy ivy
  #fi
fi

if [ "$IMAGING" ]; then
  init
  update
  setup havis-depot
  echo 'RUN ["busybox", "--install", "-s"]' > Dockerfile
  finish '/opt/havis-app' '["/sbin/init"]'
  mkdir -p rfs/bin rfs/usr/bin rfs/sbin rfs/usr/sbin rfs/tmp rfs/var/lib/dpkg/info
  cat Dockerfile
fi
