#!/bin/bash

set -x
set -e

env

mkdir -p /usr/share/man/man1

apt-get update
apt-get -y -q install apt-transport-https openjdk-8-jdk-headless ant ivy libjsch-java

echo "deb [trusted=yes] $APT ${DIST%%-*} main" > /etc/apt/sources.list.d/local.list
if [[ "${DIST##*-}" == "updates" ]] || [[ "${DIST##*-}" == "staging" ]]; then
  echo "deb [trusted=yes] $APT $DIST main" >> /etc/apt/sources.list.d/local.list
fi

apt-get update
apt-get -y -q install appbuild-essential

export PACKAGE=havis-depot

mkapp
