#!/bin/bash

set -e
set -x

env

ant -Divy.resolver=$RESOLVER -Divy.url=$IVY -Divy.default.ivy.user.dir=/tmp -Divy.settings=ivysettings_remote.xml -Dapi.url=$API -Dplatform=linux-arm -Djavac.debug=$DEBUG
