#!/bin/bash

set -e
set -x

env

rm -rf $BUILD/rfs/opt/depot/files
ant -Divy.resolver=remotefs -Divy.url=$IVY -Divy.default.ivy.user.dir=/tmp -Divy.settings=ivysettings_remote.xml -Dapi.url=$API -Dplatform=linux-arm
