#!/bin/sh

. ../../etc/default/httpd

NAME=httpd
DAEMON=/bin/busybox
PID=/run/"$NAME".pid
ARGS="httpd -f -h /opt/depot/www $ARGS"

case "$1" in
  start)
    echo -n "Starting $NAME: "
    start-stop-daemon -S -m -p $PID -x $DAEMON -b -- $ARGS
    ;;
  stop)
    echo -n "Stopping $NAME: "
    start-stop-daemon -K -p $PID
    ;;
  run)
    $DAEMON $ARGS
    ;;
  restart)
    echo -n "Stopping $NAME: "
    start-stop-daemon -K -p $PID
    sleep 1
    start-stop-daemon -S -m -p $PID -x $DAEMON -b -- $ARGS
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0