name: Build app

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architecture'
        default: 'armhf'
      dist:
        description: 'Distribution'
        default: 'stretch'
        required: true
      packaging:
        description: 'Packaging'
      imaging:
        description: 'Imaging'
      image:
        description: 'Image'
        default: 'https://github.com/peramic/Tools.Debootstrap/releases/download/v2.7.0/debian_stretch_2.7.0.tar.gz'
        required: true
      maintainer:
        description: 'Maintainer'
        default: "Open Source <opensource@peraMIC.io>"
        required: true
      support:
        description: 'Support'
        default: "support@peraMIC.io"
        required: true
      tags:
        description: 'Tags'
        default: 'ghcr.io/peramic/depot:latest'
        required: true
      platforms:
        description: 'Platforms'
        default: 'linux/arm/v7'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: ${{ github.event.inputs.imaging }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ github.event.inputs.imaging }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ github.event.inputs.imaging }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTIONS }}
      - name: Build
        id: build
        uses: peramic/actions/build-stretch@v1
        with:
          arch: ${{ github.event.inputs.arch }}
          dist: ${{ github.event.inputs.dist }}
          script: ./mkapp
          token: ${{ secrets.ACTIONS }}
          packaging: ${{ github.event.inputs.packaging }}
          imaging: ${{ github.event.inputs.imaging }}
          maintainer: ${{ github.event.inputs.maintainer }}
          support: ${{ github.event.inputs.support }}
      - run: docker run --workdir /github/workspace --rm --privileged -e ARCH -e DIST -e APT -e MIRROR -e VERSION -e IMAGE -e MAINTAINER -e SUPPORT --entrypoint bash -v "$GITHUB_WORKSPACE":"/github/workspace" debian:stretch-slim "-c" "./mkimg"
        #if: ${{ github.event.inputs.imaging }}
        env:
          ARCH: 'armhf'
          DIST: 'stretch'
          APT: 'https://peramic.github.io/debian'
          MIRROR: 'http://httpredir.debian.org/debian'
          VERSION: ${{ github.event.inputs.version }}
          IMAGE: ${{ github.event.inputs.image }}
          MAINTAINER: ${{ github.event.inputs.maintainer }}
          SUPPORT: ${{ github.event.inputs.support }}
      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ github.event.inputs.imaging }}
        with:
          context: .
          tags: ${{ github.event.inputs.tags }}
          platforms: ${{ github.event.inputs.platforms }}
          push: true
